class AddStatsToPlayer < ActiveRecord::Migration
  def change
    add_column :players, :gs14, :integer
    add_column :players, :gp14, :integer
    add_column :players, :min14, :decimal
    add_column :players, :fgm14, :decimal
    add_column :players, :fga14, :decimal
    add_column :players, :fgp14, :decimal
    add_column :players, :tpm14, :decimal
    add_column :players, :tpa14, :decimal
    add_column :players, :tpp14, :decimal
    add_column :players, :ftm14, :decimal
    add_column :players, :fta14, :decimal
    add_column :players, :ftp14, :decimal
    add_column :players, :or14, :decimal
    add_column :players, :dr14, :decimal
    add_column :players, :reb14, :decimal
    add_column :players, :blk14, :decimal
    add_column :players, :stl14, :decimal
    add_column :players, :pf14, :decimal
    add_column :players, :ast14, :decimal
    add_column :players, :to14, :decimal
    add_column :players, :ppp14, :decimal
    add_column :players, :ppg14, :decimal
    add_column :players, :gs13, :integer
    add_column :players, :gp13, :integer
    add_column :players, :min13, :decimal
    add_column :players, :fgm13, :decimal
    add_column :players, :fga13, :decimal
    add_column :players, :fgp13, :decimal
    add_column :players, :tpm13, :decimal
    add_column :players, :tpa13, :decimal
    add_column :players, :tpp13, :decimal
    add_column :players, :ftm13, :decimal
    add_column :players, :fta13, :decimal
    add_column :players, :ftp13, :decimal
    add_column :players, :or13, :decimal
    add_column :players, :dr13, :decimal
    add_column :players, :reb13, :decimal
    add_column :players, :blk13, :decimal
    add_column :players, :stl13, :decimal
    add_column :players, :pf13, :decimal
    add_column :players, :ast13, :decimal
    add_column :players, :to13, :decimal
    add_column :players, :ppp13, :decimal
    add_column :players, :ppg13, :decimal
    add_column :players, :gs12, :integer
    add_column :players, :gp12, :integer
    add_column :players, :min12, :decimal
    add_column :players, :fgm12, :decimal
    add_column :players, :fga12, :decimal
    add_column :players, :fgp12, :decimal
    add_column :players, :tpm12, :decimal
    add_column :players, :tpa12, :decimal
    add_column :players, :tpp12, :decimal
    add_column :players, :ftm12, :decimal
    add_column :players, :fta12, :decimal
    add_column :players, :ftp12, :decimal
    add_column :players, :or12, :decimal
    add_column :players, :dr12, :decimal
    add_column :players, :reb12, :decimal
    add_column :players, :blk12, :decimal
    add_column :players, :stl12, :decimal
    add_column :players, :pf12, :decimal
    add_column :players, :ast12, :decimal
    add_column :players, :to12, :decimal
    add_column :players, :ppp12, :decimal
    add_column :players, :ppg12, :decimal
    add_column :players, :gs11, :integer
    add_column :players, :gp11, :integer
    add_column :players, :min11, :decimal
    add_column :players, :fgm11, :decimal
    add_column :players, :fga11, :decimal
    add_column :players, :fgp11, :decimal
    add_column :players, :tpm11, :decimal
    add_column :players, :tpa11, :decimal
    add_column :players, :tpp11, :decimal
    add_column :players, :ftm11, :decimal
    add_column :players, :fta11, :decimal
    add_column :players, :ftp11, :decimal
    add_column :players, :or11, :decimal
    add_column :players, :dr11, :decimal
    add_column :players, :reb11, :decimal
    add_column :players, :blk11, :decimal
    add_column :players, :stl11, :decimal
    add_column :players, :pf11, :decimal
    add_column :players, :ast11, :decimal
    add_column :players, :to11, :decimal
    add_column :players, :ppp11, :decimal
    add_column :players, :ppg11, :decimal
    add_column :players, :gs10, :integer
    add_column :players, :gp10, :integer
    add_column :players, :min10, :decimal
    add_column :players, :fgm10, :decimal
    add_column :players, :fga10, :decimal
    add_column :players, :fgp10, :decimal
    add_column :players, :tpm10, :decimal
    add_column :players, :tpa10, :decimal
    add_column :players, :tpp10, :decimal
    add_column :players, :ftm10, :decimal
    add_column :players, :fta10, :decimal
    add_column :players, :ftp10, :decimal
    add_column :players, :or10, :decimal
    add_column :players, :dr10, :decimal
    add_column :players, :reb10, :decimal
    add_column :players, :blk10, :decimal
    add_column :players, :stl10, :decimal
    add_column :players, :pf10, :decimal
    add_column :players, :ast10, :decimal
    add_column :players, :to10, :decimal
    add_column :players, :ppp10, :decimal
    add_column :players, :ppg10, :decimal
    add_column :players, :gs09, :integer
    add_column :players, :gp09, :integer
    add_column :players, :min09, :decimal
    add_column :players, :fgm09, :decimal
    add_column :players, :fga09, :decimal
    add_column :players, :fgp09, :decimal
    add_column :players, :tpm09, :decimal
    add_column :players, :tpa09, :decimal
    add_column :players, :tpp09, :decimal
    add_column :players, :ftm09, :decimal
    add_column :players, :fta09, :decimal
    add_column :players, :ftp09, :decimal
    add_column :players, :or09, :decimal
    add_column :players, :dr09, :decimal
    add_column :players, :reb09, :decimal
    add_column :players, :blk09, :decimal
    add_column :players, :stl09, :decimal
    add_column :players, :pf09, :decimal
    add_column :players, :ast09, :decimal
    add_column :players, :to09, :decimal
    add_column :players, :ppp09, :decimal
    add_column :players, :ppg09, :decimal
    add_column :players, :gs08, :integer
    add_column :players, :gp08, :integer
    add_column :players, :min08, :decimal
    add_column :players, :fgm08, :decimal
    add_column :players, :fga08, :decimal
    add_column :players, :fgp08, :decimal
    add_column :players, :tpm08, :decimal
    add_column :players, :tpa08, :decimal
    add_column :players, :tpp08, :decimal
    add_column :players, :ftm08, :decimal
    add_column :players, :fta08, :decimal
    add_column :players, :ftp08, :decimal
    add_column :players, :or08, :decimal
    add_column :players, :dr08, :decimal
    add_column :players, :reb08, :decimal
    add_column :players, :blk08, :decimal
    add_column :players, :stl08, :decimal
    add_column :players, :pf08, :decimal
    add_column :players, :ast08, :decimal
    add_column :players, :to08, :decimal
    add_column :players, :ppp08, :decimal
    add_column :players, :ppg08, :decimal
    add_column :players, :gs07, :integer
    add_column :players, :gp07, :integer
    add_column :players, :min07, :decimal
    add_column :players, :fgm07, :decimal
    add_column :players, :fga07, :decimal
    add_column :players, :fgp07, :decimal
    add_column :players, :tpm07, :decimal
    add_column :players, :tpa07, :decimal
    add_column :players, :tpp07, :decimal
    add_column :players, :ftm07, :decimal
    add_column :players, :fta07, :decimal
    add_column :players, :ftp07, :decimal
    add_column :players, :or07, :decimal
    add_column :players, :dr07, :decimal
    add_column :players, :reb07, :decimal
    add_column :players, :blk07, :decimal
    add_column :players, :stl07, :decimal
    add_column :players, :pf07, :decimal
    add_column :players, :ast07, :decimal
    add_column :players, :to07, :decimal
    add_column :players, :ppp07, :decimal
    add_column :players, :ppg07, :decimal
    add_column :players, :gs06, :integer
    add_column :players, :gp06, :integer
    add_column :players, :min06, :decimal
    add_column :players, :fgm06, :decimal
    add_column :players, :fga06, :decimal
    add_column :players, :fgp06, :decimal
    add_column :players, :tpm06, :decimal
    add_column :players, :tpa06, :decimal
    add_column :players, :tpp06, :decimal
    add_column :players, :ftm06, :decimal
    add_column :players, :fta06, :decimal
    add_column :players, :ftp06, :decimal
    add_column :players, :or06, :decimal
    add_column :players, :dr06, :decimal
    add_column :players, :reb06, :decimal
    add_column :players, :blk06, :decimal
    add_column :players, :stl06, :decimal
    add_column :players, :pf06, :decimal
    add_column :players, :ast06, :decimal
    add_column :players, :to06, :decimal
    add_column :players, :ppp06, :decimal
    add_column :players, :ppg06, :decimal
    add_column :players, :gs05, :integer
    add_column :players, :gp05, :integer
    add_column :players, :min05, :decimal
    add_column :players, :fgm05, :decimal
    add_column :players, :fga05, :decimal
    add_column :players, :fgp05, :decimal
    add_column :players, :tpm05, :decimal
    add_column :players, :tpa05, :decimal
    add_column :players, :tpp05, :decimal
    add_column :players, :ftm05, :decimal
    add_column :players, :fta05, :decimal
    add_column :players, :ftp05, :decimal
    add_column :players, :or05, :decimal
    add_column :players, :dr05, :decimal
    add_column :players, :reb05, :decimal
    add_column :players, :blk05, :decimal
    add_column :players, :stl05, :decimal
    add_column :players, :pf05, :decimal
    add_column :players, :ast05, :decimal
    add_column :players, :to05, :decimal
    add_column :players, :ppp05, :decimal
    add_column :players, :ppg05, :decimal
    add_column :players, :gs04, :integer
    add_column :players, :gp04, :integer
    add_column :players, :min04, :decimal
    add_column :players, :fgm04, :decimal
    add_column :players, :fga04, :decimal
    add_column :players, :fgp04, :decimal
    add_column :players, :tpm04, :decimal
    add_column :players, :tpa04, :decimal
    add_column :players, :tpp04, :decimal
    add_column :players, :ftm04, :decimal
    add_column :players, :fta04, :decimal
    add_column :players, :ftp04, :decimal
    add_column :players, :or04, :decimal
    add_column :players, :dr04, :decimal
    add_column :players, :reb04, :decimal
    add_column :players, :blk04, :decimal
    add_column :players, :stl04, :decimal
    add_column :players, :pf04, :decimal
    add_column :players, :ast04, :decimal
    add_column :players, :to04, :decimal
    add_column :players, :ppp04, :decimal
    add_column :players, :ppg04, :decimal
    add_column :players, :gs03, :integer
    add_column :players, :gp03, :integer
    add_column :players, :min03, :decimal
    add_column :players, :fgm03, :decimal
    add_column :players, :fga03, :decimal
    add_column :players, :fgp03, :decimal
    add_column :players, :tpm03, :decimal
    add_column :players, :tpa03, :decimal
    add_column :players, :tpp03, :decimal
    add_column :players, :ftm03, :decimal
    add_column :players, :fta03, :decimal
    add_column :players, :ftp03, :decimal
    add_column :players, :or03, :decimal
    add_column :players, :dr03, :decimal
    add_column :players, :reb03, :decimal
    add_column :players, :blk03, :decimal
    add_column :players, :stl03, :decimal
    add_column :players, :pf03, :decimal
    add_column :players, :ast03, :decimal
    add_column :players, :to03, :decimal
    add_column :players, :ppp03, :decimal
    add_column :players, :ppg03, :decimal
    add_column :players, :gs02, :integer
    add_column :players, :gp02, :integer
    add_column :players, :min02, :decimal
    add_column :players, :fgm02, :decimal
    add_column :players, :fga02, :decimal
    add_column :players, :fgp02, :decimal
    add_column :players, :tpm02, :decimal
    add_column :players, :tpa02, :decimal
    add_column :players, :tpp02, :decimal
    add_column :players, :ftm02, :decimal
    add_column :players, :fta02, :decimal
    add_column :players, :ftp02, :decimal
    add_column :players, :or02, :decimal
    add_column :players, :dr02, :decimal
    add_column :players, :reb02, :decimal
    add_column :players, :blk02, :decimal
    add_column :players, :stl02, :decimal
    add_column :players, :pf02, :decimal
    add_column :players, :ast02, :decimal
    add_column :players, :to02, :decimal
    add_column :players, :ppp02, :decimal
    add_column :players, :ppg02, :decimal
    add_column :players, :gs01, :integer
    add_column :players, :gp01, :integer
    add_column :players, :min01, :decimal
    add_column :players, :fgm01, :decimal
    add_column :players, :fga01, :decimal
    add_column :players, :fgp01, :decimal
    add_column :players, :tpm01, :decimal
    add_column :players, :tpa01, :decimal
    add_column :players, :tpp01, :decimal
    add_column :players, :ftm01, :decimal
    add_column :players, :fta01, :decimal
    add_column :players, :ftp01, :decimal
    add_column :players, :or01, :decimal
    add_column :players, :dr01, :decimal
    add_column :players, :reb01, :decimal
    add_column :players, :blk01, :decimal
    add_column :players, :stl01, :decimal
    add_column :players, :pf01, :decimal
    add_column :players, :ast01, :decimal
    add_column :players, :to01, :decimal
    add_column :players, :ppp01, :decimal
    add_column :players, :ppg01, :decimal
    add_column :players, :gs00, :integer
    add_column :players, :gp00, :integer
    add_column :players, :min00, :decimal
    add_column :players, :fgm00, :decimal
    add_column :players, :fga00, :decimal
    add_column :players, :fgp00, :decimal
    add_column :players, :tpm00, :decimal
    add_column :players, :tpa00, :decimal
    add_column :players, :tpp00, :decimal
    add_column :players, :ftm00, :decimal
    add_column :players, :fta00, :decimal
    add_column :players, :ftp00, :decimal
    add_column :players, :or00, :decimal
    add_column :players, :dr00, :decimal
    add_column :players, :reb00, :decimal
    add_column :players, :blk00, :decimal
    add_column :players, :stl00, :decimal
    add_column :players, :pf00, :decimal
    add_column :players, :ast00, :decimal
    add_column :players, :to00, :decimal
    add_column :players, :ppp00, :decimal
    add_column :players, :ppg00, :decimal
    add_column :players, :gs99, :integer
    add_column :players, :gp99, :integer
    add_column :players, :min99, :decimal
    add_column :players, :fgm99, :decimal
    add_column :players, :fga99, :decimal
    add_column :players, :fgp99, :decimal
    add_column :players, :tpm99, :decimal
    add_column :players, :tpa99, :decimal
    add_column :players, :tpp99, :decimal
    add_column :players, :ftm99, :decimal
    add_column :players, :fta99, :decimal
    add_column :players, :ftp99, :decimal
    add_column :players, :or99, :decimal
    add_column :players, :dr99, :decimal
    add_column :players, :reb99, :decimal
    add_column :players, :blk99, :decimal
    add_column :players, :stl99, :decimal
    add_column :players, :pf99, :decimal
    add_column :players, :ast99, :decimal
    add_column :players, :to99, :decimal
    add_column :players, :ppp99, :decimal
    add_column :players, :ppg99, :decimal
    add_column :players, :gs98, :integer
    add_column :players, :gp98, :integer
    add_column :players, :min98, :decimal
    add_column :players, :fgm98, :decimal
    add_column :players, :fga98, :decimal
    add_column :players, :fgp98, :decimal
    add_column :players, :tpm98, :decimal
    add_column :players, :tpa98, :decimal
    add_column :players, :tpp98, :decimal
    add_column :players, :ftm98, :decimal
    add_column :players, :fta98, :decimal
    add_column :players, :ftp98, :decimal
    add_column :players, :or98, :decimal
    add_column :players, :dr98, :decimal
    add_column :players, :reb98, :decimal
    add_column :players, :blk98, :decimal
    add_column :players, :stl98, :decimal
    add_column :players, :pf98, :decimal
    add_column :players, :ast98, :decimal
    add_column :players, :to98, :decimal
    add_column :players, :ppp98, :decimal
    add_column :players, :ppg98, :decimal
    add_column :players, :gs97, :integer
    add_column :players, :gp97, :integer
    add_column :players, :min97, :decimal
    add_column :players, :fgm97, :decimal
    add_column :players, :fga97, :decimal
    add_column :players, :fgp97, :decimal
    add_column :players, :tpm97, :decimal
    add_column :players, :tpa97, :decimal
    add_column :players, :tpp97, :decimal
    add_column :players, :ftm97, :decimal
    add_column :players, :fta97, :decimal
    add_column :players, :ftp97, :decimal
    add_column :players, :or97, :decimal
    add_column :players, :dr97, :decimal
    add_column :players, :reb97, :decimal
    add_column :players, :blk97, :decimal
    add_column :players, :stl97, :decimal
    add_column :players, :pf97, :decimal
    add_column :players, :ast97, :decimal
    add_column :players, :to97, :decimal
    add_column :players, :ppp97, :decimal
    add_column :players, :ppg97, :decimal
  end
end
